export default function MethodologyPage() {
	return (
		<div className="min-h-screen bg-gray-50">
			{/* Header */}
			<div className="bg-white border-b border-gray-200">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
					<div className="text-center">
						<h1 className="text-3xl font-bold text-gray-900 mb-4">Methodology & Metrics</h1>
						<p className="text-lg text-gray-600 max-w-4xl mx-auto">
							Plain-language explanations of each metric and how we compute them. 
							These calculations align with industry standards and regulatory requirements.
						</p>
					</div>
				</div>
			</div>

			<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
				{/* Core Metrics */}
				<div className="space-y-8">
					{/* CO₂ Intensity */}
					<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
						<h2 className="text-2xl font-bold text-gray-900 mb-4">1. CO₂ Intensity (g/kWh)</h2>
						<div className="grid md:grid-cols-2 gap-6">
							<div>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h3>
								<p className="text-gray-600 mb-4">
									Carbon emitted per unit electricity generated. This is the core emissions intensity indicator 
									for CSRD/ESRS climate metrics.
								</p>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">How to read it</h3>
								<p className="text-gray-600">
									Lower is better. Spikes often indicate lower renewable availability or outages. 
									Downward trend indicates decarbonization progress.
								</p>
							</div>
							<div className="bg-gray-50 rounded-lg p-4">
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Calculation</h3>
								<p className="text-sm text-gray-600">
									<strong>Simulated:</strong> Derived from the generation mix (higher renewables → lower intensity), 
									with realistic variability (weather, outages).
								</p>
								<p className="text-sm text-gray-600 mt-2">
									<strong>Production:</strong> Total CO₂ emissions / Total electricity generated
								</p>
							</div>
						</div>
					</div>

					{/* Generation Mix */}
					<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
						<h2 className="text-2xl font-bold text-gray-900 mb-4">2. Generation Mix (MW)</h2>
						<div className="grid md:grid-cols-2 gap-6">
							<div>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h3>
								<p className="text-gray-600 mb-4">
									Electricity generated by source (hydro, wind, solar, nuclear, fossil) over time. 
									Supports ESRS disclosures on energy mix and renewable share.
								</p>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">How to read it</h3>
								<p className="text-gray-600">
									The stacked area height ≈ total output. Larger renewable area → typically lower CO₂ intensity.
								</p>
							</div>
							<div className="bg-gray-50 rounded-lg p-4">
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Calculation</h3>
								<p className="text-sm text-gray-600">
									<strong>Simulated:</strong> Supply by technology, scaled to demand with diurnal/weather factors.
								</p>
								<p className="text-sm text-gray-600 mt-2">
									<strong>Production:</strong> Real-time data from plant SCADA systems
								</p>
							</div>
						</div>
					</div>

					{/* Renewable Share */}
					<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
						<h2 className="text-2xl font-bold text-gray-900 mb-4">3. Renewable Share (%)</h2>
						<div className="grid md:grid-cols-2 gap-6">
							<div>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h3>
								<p className="text-gray-600 mb-4">
									Percentage of total generation from renewables (hydro + wind + solar). 
									Higher is generally good; expect CO₂ intensity to fall as share rises.
								</p>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Formula</h3>
								<p className="text-gray-600 font-mono text-sm bg-gray-100 p-2 rounded">
									renewable_share_pct = 100 × (hydro_mw + wind_mw + solar_mw) / total_mw
								</p>
							</div>
							<div className="bg-gray-50 rounded-lg p-4">
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Key Insights</h3>
								<ul className="text-sm text-gray-600 space-y-1">
									<li>• Direct correlation with CO₂ intensity</li>
									<li>• Supports renewable energy targets</li>
									<li>• Key metric for investor reporting</li>
									<li>• Regulatory compliance indicator</li>
								</ul>
							</div>
						</div>
					</div>

					{/* Net-zero Alignment */}
					<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
						<h2 className="text-2xl font-bold text-gray-900 mb-4">4. Net-zero Alignment (%)</h2>
						<div className="grid md:grid-cols-2 gap-6">
							<div>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h3>
								<p className="text-gray-600 mb-4">
									Annual progress vs a target emissions pathway. 100% = on or ahead of plan; &lt;100% = behind plan.
								</p>
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Formula</h3>
								<p className="text-gray-600 font-mono text-sm bg-gray-100 p-2 rounded">
									alignment_pct = 100 × target_emissions_mt / actual_emissions_mt (capped at 100%)
								</p>
							</div>
							<div className="bg-gray-50 rounded-lg p-4">
								<h3 className="text-lg font-semibold text-gray-900 mb-2">Usage</h3>
								<ul className="text-sm text-gray-600 space-y-1">
									<li>• Long-term decarbonization tracking</li>
									<li>• Regulatory compliance reporting</li>
									<li>• Investor progress updates</li>
									<li>• Strategic planning validation</li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				{/* Goal Tracker Metrics */}
				<div className="mt-12">
					<h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Goal Tracker Metrics</h2>
					<div className="space-y-8">
						{/* Real-time Alignment Index */}
						<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
							<h3 className="text-2xl font-bold text-gray-900 mb-4">Real-time Alignment Index (RAI)</h3>
							<div className="grid md:grid-cols-2 gap-6">
								<div>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h4>
									<p className="text-gray-600 mb-4">
										How current carbon intensity compares to this year's target intensity. 
										100% = on target; &gt;100% better than target; &lt;100% behind.
									</p>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Formula</h4>
									<p className="text-gray-600 font-mono text-sm bg-gray-100 p-2 rounded">
										RAI = 100 × I_target(year) / I_current
									</p>
								</div>
								<div className="bg-gray-50 rounded-lg p-4">
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Components</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• I_current: Latest CO₂ intensity reading</li>
										<li>• I_target(year): Inferred from annual targets</li>
										<li>• Proportional scaling from base year intensity</li>
									</ul>
								</div>
							</div>
						</div>

						{/* YTD Carbon Budget */}
						<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
							<h3 className="text-2xl font-bold text-gray-900 mb-4">YTD Carbon Budget</h3>
							<div className="grid md:grid-cols-2 gap-6">
								<div>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h4>
									<p className="text-gray-600 mb-4">
										Whether cumulative emissions so far are within the year-to-date (YTD) budget. 
										Positive days → ahead (good); negative → behind (bad).
									</p>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Key Calculations</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• YTD_budget_tons = annual_target_tons × (elapsed_days / 365)</li>
										<li>• YTD_tons = Σ (total_mw × Δt_hours × intensity_g_per_kWh × 1e−3)</li>
										<li>• Days ahead/behind = (YTD_budget_tons − YTD_tons) / avg_daily_emissions</li>
									</ul>
								</div>
								<div className="bg-gray-50 rounded-lg p-4">
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Usage</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• Monthly/quarterly progress tracking</li>
										<li>• Early warning system for overruns</li>
										<li>• Operational adjustment triggers</li>
										<li>• Regulatory reporting support</li>
									</ul>
								</div>
							</div>
						</div>

						{/* Decarbonization Velocity */}
						<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
							<h3 className="text-2xl font-bold text-gray-900 mb-4">Decarbonization Velocity</h3>
							<div className="grid md:grid-cols-2 gap-6">
								<div>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h4>
									<p className="text-gray-600 mb-4">
										Is intensity falling fast enough to meet the year-end target? 
										"On track" if current decline rate is sufficient; otherwise "Behind".
									</p>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Key Calculations</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• Actual velocity: Slope of intensity decline over last ~7 days</li>
										<li>• Required velocity: (I_current − I_target_year_end) × 365 / days_left</li>
										<li>• On track: v_actual ≥ v_required</li>
									</ul>
								</div>
								<div className="bg-gray-50 rounded-lg p-4">
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Units</h4>
									<p className="text-sm text-gray-600">
										<strong>g/kWh per year</strong> - Rate of intensity decline needed to meet targets
									</p>
									<h4 className="text-lg font-semibold text-gray-900 mb-2 mt-4">Usage</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• Performance vs required pace</li>
										<li>• Strategy adjustment triggers</li>
										<li>• Risk assessment tool</li>
									</ul>
								</div>
							</div>
						</div>

						{/* 2050 Pathway */}
						<div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
							<h3 className="text-2xl font-bold text-gray-900 mb-4">2050 Pathway Alignment</h3>
							<div className="grid md:grid-cols-2 gap-6">
								<div>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">What it measures</h4>
									<p className="text-gray-600 mb-4">
										Relation to the net-zero pathway and an illustrative ETA to near-zero. 
										Higher alignment is better; ETA closer to/before 2050 is better.
									</p>
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Key Metrics</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• Alignment: 100 × target_emissions_mt / actual_emissions_mt (capped at 100%)</li>
										<li>• ETA: current_year + I_current / v_actual (illustrative)</li>
										<li>• Pathway: target emissions per year to 2050 (with 2050 = 0 Mt)</li>
									</ul>
								</div>
								<div className="bg-gray-50 rounded-lg p-4">
									<h4 className="text-lg font-semibold text-gray-900 mb-2">Assumptions</h4>
									<ul className="text-sm text-gray-600 space-y-1">
										<li>• Base year: earliest year in data</li>
										<li>• 2050 target: 0 Mt emissions</li>
										<li>• Proportional intensity scaling</li>
										<li>• Illustrative ETA for guidance only</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* Data Sources & Notes */}
				<div className="mt-12 bg-blue-50 rounded-lg border border-blue-200 p-8">
					<h2 className="text-2xl font-bold text-blue-900 mb-4">Data Sources & Notes</h2>
					<div className="grid md:grid-cols-2 gap-6">
						<div>
							<h3 className="text-lg font-semibold text-blue-800 mb-2">Current Implementation</h3>
							<ul className="text-blue-700 space-y-1 text-sm">
								<li>• Simulated data for demonstration</li>
								<li>• 15-minute update intervals</li>
								<li>• Realistic weather and operational variations</li>
								<li>• Diurnal demand patterns</li>
							</ul>
						</div>
						<div>
							<h3 className="text-lg font-semibold text-blue-800 mb-2">Production Ready</h3>
							<ul className="text-blue-700 space-y-1 text-sm">
								<li>• Plant SCADA system integration</li>
								<li>• Fuel and efficiency logs</li>
								<li>• Emissions inventories</li>
								<li>• Real-time API connections</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	)
}
