-- CO₂ Intensity Forecasts Table
-- Stores predictive forecasts for CO₂ intensity

create table if not exists public.co2_forecasts (
	id bigint generated by default as identity primary key,
	"timestamp" timestamptz not null,
	co2_intensity_g_per_kwh numeric not null,
	forecast_type text not null default 'linear_regression',
	forecast_horizon_hours integer not null default 24,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

-- Indexes for performance
create index if not exists idx_co2_forecasts_timestamp on public.co2_forecasts("timestamp");
create index if not exists idx_co2_forecasts_created_at on public.co2_forecasts(created_at);
create index if not exists idx_co2_forecasts_type on public.co2_forecasts(forecast_type);

-- RLS policies
alter table public.co2_forecasts enable row level security;

-- Allow read access to all users
create policy "Allow read access to forecasts" on public.co2_forecasts
	for select using (true);

-- Allow insert/update for service role (forecasting script)
create policy "Allow service role to manage forecasts" on public.co2_forecasts
	for all using (auth.role() = 'service_role');

-- Enable realtime for forecasts
alter publication supabase_realtime add table public.co2_forecasts;
